function [ ecg ] = extraCondGroup( cg, ages)
% create extra condition group features using medical knowledge from Market
% Makers milestone 1
sev = getSeverity();
old = find(ages > 7); % 70+ and unspecified
young = find(ages <= 7);
counts = sum(cg, 2);
% Add the average severities 
sevsum = cg(:,1:end-1)*sev(:,1); % set severities to the young sevs
sevsum(old) = cg(old,1:end-1)*sev(:,2);% set severities to the old sevs
averageyoung = sum(sevsum(young))/sum(counts(young))
averageold = sum(sevsum(old))/sum(counts(old))
sev = [sev; averageyoung, averageold];
%%%%%%%%%%
sevsum = cg*sev(:,1); % set severities to the young sevs
sevsum(old) = cg(old,:)*sev(:,2);% set severities to the old sevs
sevave = sevsum./counts;

cg = boolean(cg);
cg = double(full(cg));
for i=1:size(sev,1)
    cg(young,i) = cg(young,i)*sev(i,1);
    cg(old,i) = cg(old,i)*sev(i,2);
end
%sevmax = zeros(size(cg,1),1);
sevmax = max(cg,[],2);
ecg = [sevave,sevsum,sevmax];
end
function [sev] = getSeverity()
sev = [...
    5,5;...
    2,3;...
    1,1;...
    1,1;...
    1,2;...
    1,1;...
    1,2;...
    1,2;...
    3,4;...
    3,4;...
    3,4;...
    3,4;...
    5,5;...
    4,3;...
    5,5;...
    3,4;...
    1,1;...
    1,1;...
    4,3;...
    3,2;...
    4,3;...
    1,1;...
    1,4;...
    1,1;...
    3,3;...
    1,1;...
    1,1;...
    1,1;...
    2,3;...
    3,2;...
    4,3;...
    1,1;...
    2,1;...
    2,2;...
    4,3;...
    2,3;...
    4,5;...
    1,1;...
    1,2;...
    1,1;...
    2,2;...
    2,5;...
    2,1;...
    5,5;...
    1,2;...
    ];
end

%{
AMI	5	5
RENAL1	2	3
RESPR4	1	1
INFEC4	1	1
TRAUMA	1	2
APPCHOL	1	1
ARTHSPIN	1	2
HEART4	1	2
CANCRA	3	4
CANCRB	3	4
CATAST	3	4
ROAMI	3	4
COPD	5	5
RENAL2	4	3
CHF	5	5
METAB1	3	4
FLaELEC	1	1
FXDISLC	1	1
GIBLEED	4	3
GIOBSENT	3	2
GYNECA	4	3
GYNEC1	1	1
HIPFX	1	4
ODaBNCA	1	1
LIVERDZ	3	3
MISCL1	1	1
MSC2a3	1	1
MISCL5	1	1
MISCHRT	2	3
HEMTOL	3	2
HEART2	4	3
METAB3	1	1
NEUMENT	2	1
RENAL3	2	2
CANCRM	4	3
PNCRDZ	2	3
PERVALV	4	5
PERINTL	1	1
PNEUM	1	2
PRGNCY	1	1
SEIZURE	2	2
SEPSIS	2	5
SKNAUT	2	1
STROKE	5	5
UTI	1	2
%}