function [ condGroup ] = parseConditionGroup( stringCondGroup )
condGroup = 1*strcmp(stringCondGroup,'AMI') + ...
    2*strcmp(stringCondGroup,'RENAL1') + ...
    3*strcmp(stringCondGroup,'RESPR4') + ...
    4*strcmp(stringCondGroup,'INFEC4') + ...
    5*strcmp(stringCondGroup,'TRAUMA') + ...
    6*strcmp(stringCondGroup,'APPCHOL') + ...
    7*strcmp(stringCondGroup,'ARTHSPIN') + ...
    8*strcmp(stringCondGroup,'HEART4') + ...
    9*strcmp(stringCondGroup,'CANCRA') + ...
    10*strcmp(stringCondGroup,'CANCRB') + ...
    11*strcmp(stringCondGroup,'CATAST') + ...
    12*strcmp(stringCondGroup,'ROAMI') + ...
    13*strcmp(stringCondGroup,'COPD') + ...
    14*strcmp(stringCondGroup,'RENAL2') + ...
    15*strcmp(stringCondGroup,'CHF') + ...
    16*strcmp(stringCondGroup,'METAB1') + ...
    17*strcmp(stringCondGroup,'FLaELEC') + ...
    18*strcmp(stringCondGroup,'FXDISLC') + ...
    19*strcmp(stringCondGroup,'GIBLEED') + ...
    20*strcmp(stringCondGroup,'GIOBSENT') + ...
    21*strcmp(stringCondGroup,'GYNECA') + ...
    22*strcmp(stringCondGroup,'GYNEC1') + ...
    23*strcmp(stringCondGroup,'HIPFX') + ...
    24*strcmp(stringCondGroup,'ODaBNCA') + ...
    25*strcmp(stringCondGroup,'LIVERDZ') + ...
    26*strcmp(stringCondGroup,'MISCL1') + ...
    27*strcmp(stringCondGroup,'MSC2a3') + ...
    28*strcmp(stringCondGroup,'MISCL5') + ...
    29*strcmp(stringCondGroup,'MISCHRT') + ...
    30*strcmp(stringCondGroup,'HEMTOL') + ...
    31*strcmp(stringCondGroup,'HEART2') + ...
    32*strcmp(stringCondGroup,'METAB3') + ...
    33*strcmp(stringCondGroup,'NEUMENT') + ...
    34*strcmp(stringCondGroup,'RENAL3') + ...
    35*strcmp(stringCondGroup,'CANCRM') + ...
    36*strcmp(stringCondGroup,'PNCRDZ') + ...
    37*strcmp(stringCondGroup,'PERVALV') + ...
    38*strcmp(stringCondGroup,'PERINTL') + ...
    39*strcmp(stringCondGroup,'PNEUM') + ...
    40*strcmp(stringCondGroup,'PRGNCY') + ...
    41*strcmp(stringCondGroup,'SEIZURE') + ...
    42*strcmp(stringCondGroup,'SEPSIS') + ...
    43*strcmp(stringCondGroup,'SKNAUT') + ...
    44*strcmp(stringCondGroup,'STROKE') + ...
    45*strcmp(stringCondGroup,'UTI') + ...
    46*strcmp(stringCondGroup,'');
end

