function [ procedure ] = parseProcedureGroups( stringProcGroup )
procedure = 1*strcmp(stringProcGroup,'ANES')+...
    2*strcmp(stringProcGroup,'EM')+...
    3*strcmp(stringProcGroup,'MED')+...
    4*strcmp(stringProcGroup,'PL')+...
    5*strcmp(stringProcGroup,'RAD')+...
    6*strcmp(stringProcGroup,'SAS')+...
    7*strcmp(stringProcGroup,'SCS')+...
    8*strcmp(stringProcGroup,'SDS')+...
    9*strcmp(stringProcGroup,'SEOA')+...
    10*strcmp(stringProcGroup,'SGS')+...
    11*strcmp(stringProcGroup,'SIS')+...
    12*strcmp(stringProcGroup,'SMCD')+...
    13*strcmp(stringProcGroup,'SMS')+...
    14*strcmp(stringProcGroup,'SNS')+...
    15*strcmp(stringProcGroup,'SO')+...
    16*strcmp(stringProcGroup,'SRS')+...
    17*strcmp(stringProcGroup,'SUS')+...
    18*strcmp(stringProcGroup,'');
end

