function [ drugcount_members, drug_years, drug_duration, drug_count ] = readDrugCounts()
fid = fopen('DrugCount.csv','rt');
C = textscan(fid,'%f %s %s %s','Delimiter',',','CollectOutput',1);
fclose(fid);
[drugcount_members, drugcount_members_i] = sort(C{1});
stringDrugYear = C{2}(drugcount_members_i,1);
drug_years = strcmp(stringDrugYear, 'Y1') + 2*strcmp(stringDrugYear, 'Y2') + ...
    3*strcmp(stringDrugYear, 'Y3');
%TODO this might mean something other than drug duration? what is DSFS
stringDrugDuration = C{2}(drugcount_members_i,2);
drug_duration = 0*strcmp(stringDrugDuration,'0- 1 month') + ...
    1*strcmp(stringDrugDuration,'1- 2 months') + ...
    2*strcmp(stringDrugDuration,'2- 3 months') + ...
    3*strcmp(stringDrugDuration,'3- 4 months') + ...
    4*strcmp(stringDrugDuration,'4- 5 months') + ...
    5*strcmp(stringDrugDuration,'5- 6 months') + ...
    6*strcmp(stringDrugDuration,'6- 7 months') + ...
    7*strcmp(stringDrugDuration,'7- 8 months') + ...
    8*strcmp(stringDrugDuration,'8- 9 months') + ...
    9*strcmp(stringDrugDuration,'9-10 months') + ...
    10*strcmp(stringDrugDuration,'10-11 months') + ...
    11*strcmp(stringDrugDuration,'11-12 months');
drug_count = str2double(C{2}(drugcount_members_i,3));
drug_count(find(isnan(drug_count))) = 10; % for replacing 10+ with 10
end
