function [ labcount_members, lab_years, lab_duration, lab_count ] = readLabCounts()
fid = fopen('LabCount.csv','rt');
C = textscan(fid,'%f %s %s %s','Delimiter',',','CollectOutput',1);
fclose(fid);
[labcount_members, labcount_members_i] = sort(C{1});
stringLabYear = C{2}(labcount_members_i,1);
lab_years = strcmp(stringLabYear, 'Y1') + 2*strcmp(stringLabYear, 'Y2') + ...
    3*strcmp(stringLabYear, 'Y3');
%TODO this might mean something other than lab duration? what is DSFS
stringLabDuration = C{2}(labcount_members_i,2);
lab_duration = 0*strcmp(stringLabDuration,'0- 1 month') + ...
    1*strcmp(stringLabDuration,'1- 2 months') + ...
    2*strcmp(stringLabDuration,'2- 3 months') + ...
    3*strcmp(stringLabDuration,'3- 4 months') + ...
    4*strcmp(stringLabDuration,'4- 5 months') + ...
    5*strcmp(stringLabDuration,'5- 6 months') + ...
    6*strcmp(stringLabDuration,'6- 7 months') + ...
    7*strcmp(stringLabDuration,'7- 8 months') + ...
    8*strcmp(stringLabDuration,'8- 9 months') + ...
    9*strcmp(stringLabDuration,'9-10 months') + ...
    10*strcmp(stringLabDuration,'10-11 months') + ...
    11*strcmp(stringLabDuration,'11-12 months');
lab_count = str2double(C{2}(labcount_members_i,3));
lab_count(find(isnan(lab_count))) = 10; % for replacing 10+ with 10
end
