fid = fopen('DaysInHospital_Y2.csv','rt');
C = textscan(fid,'%f %f %f','Delimiter',',','CollectOutput',1);
fclose(fid);
[DIH2_memberids, DIH2_memberids_i] = sort(C{1}(:,1));
claimsTrunc2 = C{1}(DIH2_memberids_i,2);
DIH2 = C{1}(DIH2_memberids_i,3);
fid = fopen('DaysInHospital_Y3.csv','rt');
C = textscan(fid,'%f %f %f','Delimiter',',','CollectOutput',1);
fclose(fid);
[DIH3_memberids, DIH3_memberids_i] = sort(C{1}(:,1));
claimsTrunc3 = C{1}(DIH3_memberids_i,2);
DIH3 = C{1}(DIH3_memberids_i,3);
