
load('f2.mat');
load('f3.mat');
load('f4.mat');
tic
[yr3_pred] = computeTargetDIH_b2(ages.yr2,genders.yr2,logDIH.yr2,...
    fake_target.ages,fake_target.genders,drugs.features2_1yr,drugs.features3_1yr,...
    lab.features2_1yr,lab.features3_1yr,f2.condGroup,f3.condGroup,...
    f2.procedure,f3.procedure,f2.specialty,f3.specialty,f2.place,f3.place,...
    drugs.extrafeatures2,drugs.extrafeatures3,...
    lab.extrafeatures2,lab.extrafeatures3,f2.nproviders,f3.nproviders,...
    f2.nvendors,f3.nvendors,f2.npcps,f3.npcps,f2.extraLoS,f3.extraLoS,f2.n,f3.n,...
    f2.nspec,f3.nspec,f2.nplace,f3.nplace,f2.nproc,f3.nproc,f2.ncond,f3.ncond,...
    f2.extraDSFS,f3.extraDSFS,f2.extraCharlson,f3.extraCharlson,...
    f2.extraPcpProvVend,f3.extraPcpProvVend);
yr3_pred = postProcess(yr3_pred);
err = sqrt(mean((log(DIH.yr3+1)-log(yr3_pred+1)).^2)); yr3_rmse = [yr3_rmse; err];
disp(sprintf('TEST ERROR %f',err));
toc
tic
[target.DIH] = computeTargetDIH_b2(ages.yr3,genders.yr3,logDIH.yr3,target.ages,target.genders,...
    drugs.features3_1yr,drugs.features4_1yr,lab.features3_1yr,lab.features4_1yr,...
    f3.condGroup,f4.condGroup,f3.procedure,f4.procedure,...
    f3.specialty,f4.specialty,f3.place,f4.place,...
    drugs.extrafeatures3,drugs.extrafeatures4,lab.extrafeatures3,lab.extrafeatures4,...
    f3.nproviders,f4.nproviders,f3.nvendors,f4.nvendors,f3.npcps,f4.npcps,f3.extraLoS,f4.extraLoS,...
    f3.n,f4.n,f3.nspec,f4.nspec,f3.nplace,f4.nplace,f3.nproc,f4.nproc,f3.ncond,f4.ncond,...
    f3.extraDSFS,f4.extraDSFS,f3.extraCharlson,f4.extraCharlson,...
    f3.extraPcpProvVend,f4.extraPcpProvVend);
toc
return
[yr3_pred c] = computeTargetDIH_n2(ages.yr2,genders.yr2,logDIH.yr2,...
    fake_target.ages,fake_target.genders,drugs.extrafeatures2,drugs.extrafeatures3,...
    lab.extrafeatures2,lab.extrafeatures3,f2.nproviders,f3.nproviders,...
    f2.nvendors,f3.nvendors,f2.npcps,f3.npcps,f2.extraLoS,f3.extraLoS,f2.n,f3.n,...
    f2.nspec,f3.nspec,f2.nplace,f3.nplace,f2.nproc,f3.nproc,f2.ncond,f3.ncond,...
    f2.extraDSFS,f3.extraDSFS,f2.extraCharlson,f3.extraCharlson,...
    f2.extraPcpProvVend,f3.extraPcpProvVend);
yr3_pred = postProcess(yr3_pred);
err = sqrt(mean((log(DIH.yr3+1)-log(yr3_pred+1)).^2)); yr3_rmse = [yr3_rmse; err];
disp(sprintf('TEST ERROR %f',err));

[target.DIH c4] = computeTargetDIH_n2(ages.yr3,genders.yr3,logDIH.yr3,target.ages,target.genders,...
    drugs.extrafeatures3,drugs.extrafeatures4,lab.extrafeatures3,lab.extrafeatures4,...
    f3.nproviders,f4.nproviders,f3.nvendors,f4.nvendors,f3.npcps,f4.npcps,f3.extraLoS,f4.extraLoS,...
    f3.n,f4.n,f3.nspec,f4.nspec,f3.nplace,f4.nplace,f3.nproc,f4.nproc,f3.ncond,f4.ncond,...
    f3.extraDSFS,f4.extraDSFS,f3.extraCharlson,f4.extraCharlson,...
    f3.extraPcpProvVend,f4.extraPcpProvVend);
return
